CREATE TABLE USUARIOS (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    email VARCHAR(150) UNIQUE NOT NULL,
    fecha_creacion DATE DEFAULT CURRENT_DATE
);
CREATE TABLE PRODUCTOS (
    id SERIAL PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    precio NUMERIC(10, 2),
    stock INTEGER DEFAULT 0,
    fecha_creacion DATE DEFAULT CURRENT_DATE
);
CREATE TABLE ORDENES (
    id SERIAL PRIMARY KEY,
    usuario_id INT NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
    producto_id INT NOT NULL REFERENCES productos(id) ON DELETE RESTRICT,
    cantidad INTEGER NOT NULL,
    fecha_orden DATE DEFAULT CURRENT_DATE
);